### ISSUE TITLE
Could not find com.android.support:appcompat-v7:27.0.2.

### ISSUE THREAD

**Issue by vipulism** [IndoorAtlas/cordova-plugin#29]
getting this error in my ionic v1 app
my ionic info

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 6.4.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 6.0.0
    Ionic Framework   : ionic1 1.3.4

System:

    Android SDK Tools : 25.2.5
    Node              : v6.9.1
    npm               : 4.3.0
    OS                : Windows 10

**Comment by toninopanen** [comment]
Hi and sorry for the delay!

If you are still having problems with this error, you should try updating Android Support Library and Android Support Repository. These can be found in Android SDK Manager.

Thanks,
Toni
