### ISSUE TITLE
iOS - "API secret must not contain white space"

### ISSUE THREAD

**Issue by MattFisch** [IndoorAtlas/cordova-plugin#40]
Hello,

I'm using the Cordova SDK Version 3.1.2, when calling IndoorAtlat.initialize("API_KEY");
I get the following Message in the console:

> App[9828:18747419] -!- IndoorAtlas SDK :: API secret must not contain white space

I located the line, where the secret is set within the sourcecode (IndoorAtlasLocationService.m) and removed the whitespace:

`[self.manager setApiKey:self.apikey andSecret:@""];`

this removed the message but now when running it, the following error appears and it crashes:

> Assertion failed: (!strcmp(dispatch_queue_get_label(__null), ("com.apple.main-thread"))), function -[IAWebsocketPositioner init], file /Library/jenkins_home/workspace/ios-sdk-master/framework/IAPositioner/IAWebsocketPositioner.mm, line 111.

Everything is working fine on Android.

**Comment by matti-ida** [comment]
Hi Matt,

thanks for the bug report!

We just released a new cordova-plugin version with SDK 3.1.3, which should fix the issue.
