### ISSUE TITLE
`destination is not defined` after wayfinding stop action called

### ISSUE THREAD

**Issue by Pietfro** [IndoorAtlas/cordova-plugin#41]
I encountered an issue which occurs after I call JS `removeWayfindingUpdates()`.
Basically, the stopWayfinding function expects `destination` object which is not defined at this point.
```
  function stopWayfinding() {
    native('removeWayfindingUpdates', [destination.latitude, destination.longitude, destination.floor]);
  }
```
After analyzing the native method I figured we do not need `destination` there as `removeWayfindingUpdates()` does not take any arguments:
```
    private void removeWayfindingUpdates() {
        getListener(this).removeWayfindingUpdates();
        cordova.getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
              mLocationManager.removeWayfindingUpdates();
            }
        });
    }
```
Correct me if I am wrong, but I'd go ahead and remove `destination` reference from there. 
Btw. Great plugin!

**Comment by gitjuba** [comment]
Hi @Pietfro ! Thanks for the report! Indeed this appears to be a bug in the plugin. We'll fix it ASAP.
