### ISSUE TITLE
Could not GET maven-metadata.xml

### ISSUE THREAD

**Issue by phasooni** [IndoorAtlas/cordova-plugin#43]
Hey, today we found this issue related to android repository:
`Could not GET 'https://indooratlas-ltd.bintray.com/mvn-public/androidx/core/core/maven-metadata.xml'. Received status code 403 from server: Forbidden`

Has something changed recently in regards to that?

**Comment by matti-ida** [comment]
Hi,

we have recently migrated from Bintray to CloudSmith, so you should update your Gradle build files and/or Cordova plugin as described here:
https://indooratlas.freshdesk.com/support/solutions/articles/36000279809-updating-your-builds-using-indooratlas-sdk-due-to-migrating-from-bintray-to-cloudsmith

It seems indeed that Bintray is currently having a scheduled maintenance break, which probably causes the issue: https://status.bintray.com

See also https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by phasooni** [comment]
Thanks @matti-ida!
