### ISSUE TITLE
Unable to build in Xcode 

### ISSUE THREAD

**Issue by quannguyen81** [IndoorAtlas/cordova-plugin#7]
Hi,

I'm not sure if I'm doing anything wrong or missing anything but I noticed these issues when trying to use the plugin. I couldn't find any information about this on the internet so I thought I post my questions here. Hopefully someone could help.

1. When I add the plugin I got the message below:

cp: no such file or directory: /Users/quannguyen/Documents/hg/winkers/winkersapp/plugins/cordova-plugin-indooratlas/src/ios/IndoorAtlas2.3/IndoorAtlas.framework/Resources

2. When I tried to build in Xcode, I got this message below:

Failed to load Info.plist from bundle at path /Users/quannguyen/Library/Developer/CoreSimulator/Devices/AD8C22E2-96FC-4D92-9F19-4714FDF44370/data/Library/Caches/com.apple.mobile.installd.staging/temp.vX8ShE/extracted/Payload/Winkers.app/Frameworks/IndoorAtlas.framework

Thanks so much in advance!
Quan

**Comment by toninopanen** [comment]
Hi qazn123, 
Try updating Cordova and then building the project again
