### ISSUE TITLE
IOS Plugin Not compiling

### ISSUE THREAD

**Issue by yuukan** [IndoorAtlas/cordova-plugin#8]
Just noticed that with the master plugin it won't compile on Xcode. 
And the issue is that on the "Indoor Atlas Framework" inside Plugins>cordova-plugin-indooratlas>src>ios>IndoorAtlas2.4, if you open it on the finder you will find that you have this sub-menu structure: Versions>2.4.1-66>"Needed files", when I compile it it will give me an error. 

Then I moved the files outside of the Versions>2.4.1-66 folder and it compiled correctly.

Let me know if I didn't explained correctly or if you need more info

**Comment by toninopanen** [comment]
Thanks for the information @yuukan 
It seems like Cordova doesn't fetch the symbolic links anymore, to bypass this problem please use --nofetch flag when adding IndoorAtlas Plugin.

`cordova plugin add --nofetch https://github.com/IndoorAtlas/cordova-plugin.git`
